# Generated by Django 5.0.2 on 2024-02-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('retailerID', models.AutoField(primary_key=True, serialize=False)),
                ('retailerName', models.CharField(max_length=255)),
            ],
        ),
    ]
