# Generated by Django 5.0.2 on 2024-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageLink',
            field=models.CharField(default='no image', max_length=10000),
            preserve_default=False,
        ),
    ]
