# Generated by Django 5.0.2 on 2024-02-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_product_imagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authusergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authpermission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='authuseruserpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='authuseruserpermissions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='djangoadminlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='user',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='djangoadminlog',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DoNotMix',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='ingredID',
        ),
        migrations.DeleteModel(
            name='ListProduct',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='prodID',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
        migrations.DeleteModel(
            name='RoutineProduct',
        ),
        migrations.DeleteModel(
            name='SkincareQuizAnswers',
        ),
        migrations.DeleteModel(
            name='SkincareRoutine',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ProductIngredient',
        ),
    ]
