# Generated by Django 5.0.2 on 2024-02-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_authusergroups_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_id', models.IntegerField()),
                ('retailer_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_concerns', models.CharField(choices=[('redness', 'Redness'), ('dryness', 'Dryness'), ('irritation', 'Irritation'), ('uneven-ness', 'Uneven-ness'), ('dullness', 'Dullness'), ('fine lines', 'Fine lines'), ('texture', 'Texture'), ('oiliness', 'Oiliness'), ('sun protection', 'Sun protection'), ('hydration', 'Hydration'), ('brightening', 'Brightening'), ('acne', 'Acne'), ('blackheads', 'Blackheads'), ('dehydration', 'Dehydration'), ('aging', 'Aging')], max_length=255)),
                ('product_features', models.CharField(choices=[('non-comedogenic', 'Non-comedogenic'), ('cruelty-free', 'Cruelty-free'), ('vegan', 'Vegan'), ('sulfate-free', 'Sulfate-free'), ('paraben-free', 'Paraben-free'), ('unscented', 'Unscented'), ('fragrance-free', 'Fragrance-free'), ('phthalate-free', 'Phthalate-free'), ('clean ingredients', 'Clean ingredients'), ('sustainable packaging', 'Sustainable packaging'), ('dye-free', 'Dye-free'), ('lightweight', 'Lightweight'), ('non-greasy', 'Non-greasy'), ('quick-absorbing', 'Quick-absorbing'), ('water-resistant', 'Water-resistant'), ('oil-free', 'Oil-free'), ('alcohol-free', 'Alcohol-free'), ('silicone-free', 'Silicone-free'), ('natural ingredients', 'Natural ingredients')], max_length=255)),
                ('ingredient_list', models.TextField()),
                ('recommended_weekly_usage_frequency', models.SmallIntegerField()),
                ('skin_type_preference', models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=255)),
                ('active_ingredients', models.TextField()),
                ('image_link', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
