# Generated by Django 5.0.2 on 2024-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('Oily', 'Oily'), ('Dry', 'Dry'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive'), ('Normal', 'Normal')], max_length=100)),
                ('age_range', models.CharField(choices=[('Prefer Not to Say', 'Prefer Not to Say'), ('10s', '10s'), ('20s', '20s'), ('30s', '30s'), ('40s', '40s'), ('50s', '50s'), ('60s', '60s'), ('70s+', '70s+')], max_length=100)),
                ('concerns', models.CharField(choices=[('Acne', 'Acne'), ('Sun Damage', 'Sun Damage'), ('Hyperpigmentation', 'Hyperpigmentation'), ('Dullness', 'Dullness'), ('Fine Lines', 'Fine Lines'), ('Intense Dryness', 'Intense Dryness'), ('Redness', 'Redness'), ('Texture', 'Texture'), ('Blackheads', 'Blackheads')], max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personal_values', models.CharField(choices=[('100% natural', '100% natural'), ('Cruelty-Free', 'Cruelty-Free'), ('Clean Manufacturing', 'Clean Manufacturing'), ('Ethical Leadership', 'Ethical Leadership'), ('Locally Manufactured', 'Locally Manufactured'), ('Organic', 'Organic'), ('Recyclable Packaging', 'Recyclable Packaging'), ('Inclusivity', 'Inclusivity'), ('Plastic-Free', 'Plastic-Free')], max_length=100)),
                ('allergies', models.CharField(choices=[('Fragrance', 'Fragrance'), ('Preservatives', 'Preservatives'), ('Nickel', 'Nickel'), ('Sulfates', 'Sulfates'), ('Essential Oils', 'Essential Oils'), ('Propylene Glycol', 'Propylene Glycol'), ('Retinoids', 'Retinoids'), ('Lanolin (Wool)', 'Lanolin (Wool)'), ('Latex', 'Latex'), ('Methylisothiazolinone (MI)', 'Methylisothiazolinone (MI)'), ('Cocamidopropyl Betaine', 'Cocamidopropyl Betaine')], max_length=100)),
                ('lifestyle', models.CharField(choices=[('Wear Makeup', 'Wear Makeup'), ('Often Outside', 'Often Outside'), ('Irregular/Lack of Sleep', 'Irregular/Lack of Sleep'), ('Stressed', 'Stressed'), ('Dehydrated', 'Dehydrated')], max_length=100)),
                ('skincare_routine', models.CharField(choices=[('Cleanser', 'Cleanser'), ('Toner', 'Toner'), ('Serum', 'Serum'), ('Exfoliant', 'Exfoliant'), ('Moisturizer', 'Moisturizer'), ('Sunscreen', 'Sunscreen')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
