# Generated by Django 5.0.2 on 2024-02-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='age_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='allergies',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='concerns',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='lifestyle',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='personal_values',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='skin_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='skincare_routine',
            field=models.JSONField(),
        ),
    ]
