# Generated by Django 5.0.2 on 2024-02-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0001_initial'),
    ]

    operations = [
    ]
