# Generated by Django 5.0.2 on 2024-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0002_remove_quizresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
