# Generated by Django 5.0.2 on 2024-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0003_alter_quizresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
