# Generated by Django 5.0.2 on 2024-02-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0004_alter_quizresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='skin_type',
            field=models.JSONField(max_length=100),
        ),
    ]
