# Generated by Django 5.0.2 on 2024-02-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0003_remove_quizresult_created_at_and_more'),
        ('skinquiz', '0006_auto_20240221_2039'),
    ]

    operations = [
    ]
