# Generated by Django 5.0.2 on 2024-02-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinquiz', '0007_merge_20240223_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='age_range',
        ),
    ]
